name: Publish to GitHub Packages

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Configure package for GitHub Packages
        run: |
          # Create a temporary package.json for GitHub Packages publishing
          # GitHub Packages requires the scope to match the repository owner
          cat package.json | jq '.name = "@ericdunaway/mcp-miro"' | \
          jq '.publishConfig.registry = "https://npm.pkg.github.com"' | \
          jq '.publishConfig.access = "public"' > package-github.json
          mv package-github.json package.json

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}